@client_id = 94222026-ce94-4de9-bc77-8bd66b3b7f10
@client_secret = 9f58867b-aa4f-425a-81cf-dea812dc1f2a

POST http://localhost:9000/oauth2/token
Authorization: Basic {{client_id}} {{client_secret}}
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials
&scope=api_api1 api_api2

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("token_type", response.body.token_type);
%}
###


GET localhost:8080/v1/free
Authorization: {{token_type}} {{access_token}}
###

GET localhost:8080/v1/silver
Authorization: {{token_type}} {{access_token}}
###

GET localhost:8080/v1/gold
Authorization: {{token_type}} {{access_token}}
###

GET localhost:8080/v1/platinum
Authorization: {{token_type}} {{access_token}}
